import "./globals.scss";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Lexend_Deca, Inconsolata } from "next/font/google";

// const lexend_900 = Lexend_Deca({
//   weight: "900",
//   subsets: ["latin"],
// });
const inconsolata = Inconsolata({
  weight: ["300", "400", "900"],
  subsets: ["latin"],
});

// const major_mono = Major_Mono_Display({})
export const metadata: Metadata = {
  title: "Lam Tran Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inconsolata.className}>{children}</body>
      <Analytics />
    </html>
  );
}
