import "./globals.scss";
import type { Metadata } from "next";

import { Lexend_Deca } from "next/font/google";

// const lexend_900 = Lexend_Deca({
//   weight: "900",
//   subsets: ["latin"],
// });
const lexend = Lexend_Deca({
  weight: ["300", "400", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lam Tran Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lexend.className}>{children}</body>
    </html>
  );
}
